export const Objets=[
    {id:1,
        titre:"squide game",
        image:"../src/assets/squide_game.png",
        url:"https://taketomi001.github.io/squid_game/",
        description:"Trouver la carte pour participer au jeu squide game",
    },
    {id:2,
        titre:"Pokéxplorer",
        image:"../src/assets/pokexplorer.png",
        url:"https://wildcodeschool.github.io/2024-12-orleans-cda-project2-team-c/",
        description:"Parcourez la liste des Pokémon avec ce que vous avez trouvé !",
    },
    {id:3,
        titre:"Relax",
        image:"../src/assets/relax.png",
        url:"https://chloeseclier.github.io/Hackathon2025-TEC/",
        description:"Découvrez votre niveau de stress et voyez ce qu'il vous faut pour vous détendre.",
    },
]